openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
  description: A simple API for managing books, authors, and publishers.
servers:
  - url: 'http://creativelibrary.example.com/api'
paths:
  /books:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created
    put:
      summary: Update a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated
  /books/{id}:
    get:
      summary: Get a book by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the book to retrieve
      responses:
        '204':
          description: Book deleted
        '404':
          description: Book not found
    delete:
      summary: Delete a book by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the book to delete
      responses:
        '204':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
  /authors:
    get:
      summary: Get a list of authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    post:
      summary: Create a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author created
    put:
      summary: Update an author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated
  /authors/{id}:
    get:
      summary: Get an author by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the author to retrieve
      responses:
        '200':
          description: A single author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Author not found
    delete:
      summary: Delete an author by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the author to delete
      responses:
        '204':
          description: Author deleted
        '404':
          description: Author not found
  /publishers:
    get:
      summary: Get a list of publishers
      responses:
        '200':
          description: A list of publishers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publisher'
    post:
      summary: Create a new publisher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publisher'
      responses:
        '201':
          description: Publisher created
    put:
      summary: Update a publisher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publisher'
      responses:
        '200':
          description: Publisher updated
  /publishers/{id}:
    get:
      summary: Get a publisher by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the publisher to retrieve
      responses:
        '200':
          description: A single publisher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
        '404':
          description: Publisher not found
    delete:
      summary: Delete a publisher by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: The id of the publisher to delete
      responses:
        '204':
          description: Publisher deleted
        '404':
          description: Publisher not found
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        genre:
          type: string
          example: Fantasy
        author:
          $ref: '#/components/schemas/Author'
        publisher:
          $ref: '#/components/schemas/Publisher'
      required:
        - id
        - title
        - author
        - publisher
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        biography:
          type: string
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
      required:
        - id
        - name
    Publisher:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        founded:
          type: integer
          format: int32
          description: The year the publisher was founded.
        location:
          type: string
          description: The main location of the publisher.
        booksPublished:
          type: array
          items:
            $ref: '#/components/schemas/Book'
      required:
        - id
        - name