openapi: 3.0.0
info:
  title: CreativeLibrary API
  version: 1.0.0
  description: A simple API for managing books, authors, and publishers.
servers:
  - url: 'http://creativelibrary.example.com/api'
paths:
  /books:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /libraries:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /authors:
    get:
      summary: Get a list of authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /publishers:
    get:
      summary: Get a list of publishers
      responses:
        '200':
          description: A list of publishers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publisher'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        genre:
          type: string
          example: Fantasy
        authorId:
          type: integer
          format: int64
        publisherId:
          type: integer
          format: int64
      required:
        - id
        - title
        - authorId
        - publisherId
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        biography:
          type: string
      required:
        - id
        - name
    Publisher:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        founded:
          type: integer
          format: int32
          description: The year the publisher was founded.
        location:
          type: string
          description: The main location of the publisher.
      required:
        - id
        - name